/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Project_2;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;

/**
 *
 * @author zoyamahmood
 */
public class AddStudentGrades extends javax.swing.JFrame {

    /**
     * Creates new form AddStudentGrades
     */
    public AddStudentGrades() {
        initComponents();
        loadStudentIDs();
        loadSemesters();
        loadGrades();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BtnHome = new javax.swing.JButton();
        Title = new javax.swing.JLabel();
        jLabelStudID = new javax.swing.JLabel();
        jLabe = new javax.swing.JTextField();
        jLabelGrades = new javax.swing.JLabel();
        TfClass2 = new javax.swing.JTextField();
        Class2GradeLABEL = new javax.swing.JLabel();
        TfClass3 = new javax.swing.JTextField();
        Class3GradeLABEL = new javax.swing.JLabel();
        TfClass4 = new javax.swing.JTextField();
        Class4GradeLABEL = new javax.swing.JLabel();
        jLabelSemester = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jScrollPaneClasses = new javax.swing.JList<>();
        cbStudentID = new javax.swing.JComboBox<>();
        jScrollPane8 = new javax.swing.JScrollPane();
        ListSemester1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        BtnHome.setBackground(new java.awt.Color(2, 154, 154));
        BtnHome.setFont(new java.awt.Font("Toppan Bunkyu Midashi Gothic", 1, 11)); // NOI18N
        BtnHome.setForeground(new java.awt.Color(208, 244, 244));
        BtnHome.setText("Back Home");
        BtnHome.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHomeActionPerformed(evt);
            }
        });

        Title.setBackground(new java.awt.Color(0, 0, 102));
        Title.setFont(new java.awt.Font("Toppan Bunkyu Midashi Gothic", 1, 24)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Enter Student Grades");
        Title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelStudID.setFont(new java.awt.Font("Toppan Bunkyu Midashi Gothic", 0, 15)); // NOI18N
        jLabelStudID.setForeground(new java.awt.Color(208, 244, 244));
        jLabelStudID.setText("* Student ID:");

        jLabe.setFont(new java.awt.Font("Toppan Bunkyu Gothic", 0, 13)); // NOI18N

        jLabelGrades.setFont(new java.awt.Font("Toppan Bunkyu Midashi Gothic", 0, 15)); // NOI18N
        jLabelGrades.setForeground(new java.awt.Color(208, 244, 244));
        jLabelGrades.setText("*Class 1 Grade");

        TfClass2.setFont(new java.awt.Font("Toppan Bunkyu Gothic", 0, 13)); // NOI18N

        Class2GradeLABEL.setFont(new java.awt.Font("Toppan Bunkyu Midashi Gothic", 0, 15)); // NOI18N
        Class2GradeLABEL.setForeground(new java.awt.Color(208, 244, 244));
        Class2GradeLABEL.setText("Class 2 Grade");

        TfClass3.setFont(new java.awt.Font("Toppan Bunkyu Gothic", 0, 13)); // NOI18N

        Class3GradeLABEL.setFont(new java.awt.Font("Toppan Bunkyu Midashi Gothic", 0, 15)); // NOI18N
        Class3GradeLABEL.setForeground(new java.awt.Color(208, 244, 244));
        Class3GradeLABEL.setText("Class 3 Grade");

        TfClass4.setFont(new java.awt.Font("Toppan Bunkyu Gothic", 0, 13)); // NOI18N

        Class4GradeLABEL.setFont(new java.awt.Font("Toppan Bunkyu Midashi Gothic", 0, 15)); // NOI18N
        Class4GradeLABEL.setForeground(new java.awt.Color(208, 244, 244));
        Class4GradeLABEL.setText("Class 4 Grade");

        jLabelSemester.setFont(new java.awt.Font("Toppan Bunkyu Midashi Gothic", 0, 15)); // NOI18N
        jLabelSemester.setForeground(new java.awt.Color(208, 244, 244));
        jLabelSemester.setText("*Semester:");

        jScrollPaneClasses.setFont(new java.awt.Font("Toppan Bunkyu Gothic", 0, 13)); // NOI18N
        jScrollPane7.setViewportView(jScrollPaneClasses);

        cbStudentID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ListSemester1.setFont(new java.awt.Font("Toppan Bunkyu Gothic", 0, 13)); // NOI18N
        ListSemester1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "1", "2", "Summer School" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane8.setViewportView(ListSemester1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BtnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelStudID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(174, 174, 174))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelSemester)
                                    .addComponent(Class3GradeLABEL)
                                    .addComponent(Class2GradeLABEL)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cbStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(94, 94, 94)
                                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(Class4GradeLABEL)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(TfClass4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                    .addComponent(TfClass3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TfClass2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabe, javax.swing.GroupLayout.Alignment.LEADING))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelGrades)
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(39, 39, 39)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                    .addGap(644, 644, 644)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Title)
                    .addComponent(BtnHome))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelStudID)
                        .addGap(8, 8, 8)
                        .addComponent(cbStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelSemester)
                .addGap(97, 97, 97)
                .addComponent(jLabelGrades)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(Class2GradeLABEL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TfClass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(Class3GradeLABEL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TfClass3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(Class4GradeLABEL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TfClass4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(200, 200, 200)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(356, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHomeActionPerformed
        new MainMenu().setVisible(true);
    }//GEN-LAST:event_BtnHomeActionPerformed
private void loadStudentIDs() {
        try (Connection conn = DriverManager.getConnection("jdbc:derby://localhost:1527/SMS");
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery("SELECT student_id FROM Student_Details")) {

            while (rs.next()) {
                cbStudentID.addItem(rs.getString("student_id"));
            }

        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error loading student IDs: " + ex.getMessage());
        }
    }
private void loadGrades() {
    // Implement this method to load grades from your database or any other source
    // For example:
    DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
    model.addElement("A+");
    model.addElement("A");
    model.addElement("A-");
    model.addElement("B+");
    model.addElement("B");
    model.addElement("B-");
    model.addElement("C+");
    model.addElement("C");
    model.addElement("C-");
    model.addElement("D+");
    model.addElement("D");
    model.addElement("D-");
}
private void loadSemesters() {
    // Implement this method to load semesters from your database or any other source
    // For example:
    DefaultListModel<String> model = new DefaultListModel<>();
    model.addElement("1");
    model.addElement("2");
    model.addElement("Summer School");
    ListSemester1.setModel(model);
}


private void loadClassesForStudent(String studentID, String semester) {
    DefaultListModel<String> model = new DefaultListModel<>();

    // Query the database to fetch class codes for the selected student ID and semester from the Enrollments table
    try (Connection conn = DriverManager.getConnection("jdbc:derby://localhost:1527/SMS");
         PreparedStatement ps = conn.prepareStatement("SELECT class1_code, class2_code, class3_code, class4_code FROM Enrollments WHERE student_id = ? AND semester = ?")) {

        ps.setString(1, studentID);
        ps.setString(2, semester);
        ResultSet rs = ps.executeQuery();

        // Add each class code to the model
        if (rs.next()) {
            String class1 = rs.getString("class1_code");
            String class2 = rs.getString("class2_code");
            String class3 = rs.getString("class3_code");
            String class4 = rs.getString("class4_code");

            if (class1 != null) {
                model.addElement(class1);
            }
            if (class2 != null) {
                model.addElement(class2);
            }
            if (class3 != null) {
                model.addElement(class3);
            }
            if (class4 != null) {
                model.addElement(class4);
            }
        }

        jScrollPaneClasses.setModel(model);
    } catch (SQLException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error loading classes for student: " + ex.getMessage());
    }
}


private void saveGrade() {
    String studentID = (String) cbStudentID.getSelectedItem();
    String semester = (String) ListSemester1.getSelectedValue(); // Assuming semester is selected from ListSemester1
    String classCode = (String) jScrollPaneClasses.getSelectedValue();

    if (studentID != null && semester != null && classCode != null) {
        try (Connection conn = DriverManager.getConnection("jdbc:derby://localhost:1527/SMS")) {
            // Check if the record already exists
            PreparedStatement checkStmt = conn.prepareStatement(
                    "SELECT COUNT(*) FROM Grades WHERE student_id = ? AND semester = ? AND class_code = ?");
            checkStmt.setString(1, studentID);
            checkStmt.setString(2, semester);
            checkStmt.setString(3, classCode);
            ResultSet rs = checkStmt.executeQuery();
            rs.next();
            int count = rs.getInt(1);

            if (count > 0) { // If record exists, update
                PreparedStatement updateStmt = conn.prepareStatement(
                        "UPDATE Grades SET grade = ? WHERE student_id = ? AND semester = ? AND class_code = ?");
                updateStmt.setString(2, studentID);
                updateStmt.setString(3, semester);
                updateStmt.setString(4, classCode);
                updateStmt.executeUpdate();
            } else { // If record does not exist, insert
                PreparedStatement insertStmt = conn.prepareStatement(
                        "INSERT INTO Grades (student_id, semester, class_code, grade) VALUES (?, ?, ?, ?)");
                insertStmt.setString(1, studentID);
                insertStmt.setString(2, semester);
                insertStmt.setString(3, classCode);
                insertStmt.executeUpdate();
            }

            JOptionPane.showMessageDialog(this, "Grade saved successfully!");

        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error saving grade: " + ex.getMessage());
        }
    } else {
        JOptionPane.showMessageDialog(this, "Please select a student, semester, class, and grade.");
    }
}



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddStudentGrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddStudentGrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddStudentGrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddStudentGrades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddStudentGrades().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnHome;
    private javax.swing.JLabel Class2GradeLABEL;
    private javax.swing.JLabel Class3GradeLABEL;
    private javax.swing.JLabel Class4GradeLABEL;
    private javax.swing.JList<String> ListSemester1;
    private javax.swing.JTextField TfClass2;
    private javax.swing.JTextField TfClass3;
    private javax.swing.JTextField TfClass4;
    private javax.swing.JLabel Title;
    private javax.swing.JComboBox<String> cbStudentID;
    private javax.swing.JTextField jLabe;
    private javax.swing.JLabel jLabelGrades;
    private javax.swing.JLabel jLabelSemester;
    private javax.swing.JLabel jLabelStudID;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JList<String> jScrollPaneClasses;
    // End of variables declaration//GEN-END:variables
}
